# Generated by Django 3.1.7 on 2021-02-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mcqoptions',
            options={'verbose_name_plural': 'MCQ Options'},
        ),
        migrations.AlterModelOptions(
            name='studentquestion',
            options={'verbose_name_plural': 'Student Question'},
        ),
        migrations.AlterField(
            model_name='fillintheblank',
            name='correct_answer',
            field=models.CharField(max_length=200, verbose_name='Correct Answer'),
        ),
    ]
