# Generated by Django 3.1.7 on 2021-03-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0003_progress_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentquestion',
            name='is_attempted',
            field=models.BooleanField(default=False, verbose_name='Attempted?'),
            preserve_default=False,
        ),
    ]
