# Generated by Django 3.1.7 on 2021-03-05 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0005_auto_20210303_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='progress',
            name='is_in_progress',
            field=models.BooleanField(default=False),
        ),
    ]
