# Generated by Django 3.1.7 on 2021-03-05 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz_app', '0006_auto_20210305_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='time_limit',
            field=models.IntegerField(default=0),
        ),
    ]
